# Jupyter notebook quick tour
## working with cells
To run cell:
- select inside cell
- <kbd>SHIFT</kbd>+<kbd>ENTER</kbd>

In [1]:
print('sup globe!')

sup globe!


## Importing libraries

To import a library:
```python
import name_of_library
```

In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
#import pizza

## Variables

In [3]:
name ='your name'
age = '99'

In [4]:
name

'your name'

### variable types
```python
type(var)
```

In [5]:
type(name)

str

In [6]:
type(age)

str

Change variable **`age`** to an integer.

In [7]:
age = 99

In [8]:
type(age)

int

## Functions

In [9]:
def intro(var):
    hello = "Hello! My name is {}".format(var)
    return hello

In [10]:
intro(name)

'Hello! My name is your name'

## Working with numpy
NumPy is the fundamental package for scientific computing with Python. It contains among other things:
- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

### Create a 1d array

In [11]:
a = np.array([2,3,4])

print(a)

[2 3 4]


In [12]:
a.size

3

### Create 2d array

In [13]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


### Get the shape of the array

In [14]:
b.shape

(2, 3)

## Basic Operations
Unlike in many matrix languages, the product operator `*` operates elementwise in NumPy arrays. The matrix product can be performed using the `dot` function or method:


$A =\begin{bmatrix}
1 & 2  \\
3 & 4\end{bmatrix}\\
B = \begin{bmatrix}
    5 & 6 \\
    7 & 8
\end{bmatrix}
$


$C = \begin{bmatrix}
1 & 2 & 3  \\
4 & 5 & 6\end{bmatrix}\\
D = \begin{bmatrix}
7 & 8 & 9 \\
10 & 11 & 12\end{bmatrix}
$


### <center> Element wise</center>
$$
A*B 
 = \begin{bmatrix}
    1 & 2 \\
    3 & 4
\end{bmatrix}
 \begin{bmatrix}
    5 & 6 \\
    7 & 8
\end{bmatrix}
=
 \begin{bmatrix}
    1(5) & 2(6) \\
    3(7) & 4(8)
\end{bmatrix}
= \begin{bmatrix}
    5 & 12 \\
    21 & 32
\end{bmatrix}
$$

### <center> Dot Product (_Matrix product_)</center>
$
A\cdot B 
 = \begin{bmatrix}
    1 & 2 \\
    3 & 4
\end{bmatrix}
 \begin{bmatrix}
    5 & 6 \\
    7 & 8
\end{bmatrix}
$
$= \begin{bmatrix}
    1(5) + 2(7) & 1(6)+ 2(8) \\
    3(5)+ 4(7) & 3(6) + 4(8)
\end{bmatrix}
$
$= \begin{bmatrix}
    5 + 14 & 6+ 16 \\
    15+ 28 & 18 + 32
\end{bmatrix}
$
$= \begin{bmatrix}
    19 & 22 \\
    43 & 50
\end{bmatrix}
$

Some Markdown text with <span style="color:blue">some *blue* text</span>.

In [15]:
A = np.array([[1,2],[3,4]])

B = np.array([[5,6],[7,8]])

C = np.array([[1,2,3],[4,5,6]])

D = np.array([[7,8,9],[10,11,12]])

In [16]:
A*B

array([[ 5, 12],
       [21, 32]])

In [17]:
A.dot(B)

array([[19, 22],
       [43, 50]])

In [18]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

### create an array of 1's

In [19]:
one = np.ones((2,3))
one

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### Create an array of 0's

In [20]:
zero = np.zeros((4,4))
zero

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

### Slicing
Create a 3x4 array

In [21]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
b[0]

array([0, 1, 2, 3])

In [23]:
b[2]

array([ 8,  9, 10, 11])

In [24]:
b[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [25]:
# from the 0th row give me the 3rd element
b[0,3]

3

In [26]:
# from the 1st row, give me 0'th upto but not including 2nd element
b[1,0:2]

array([4, 5])